spring.application.name=accordia
server.port=8080


spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=
spring.r2dbc.driver-class-name=org.postgresql.Driver

# Enable SQL initialization for R2DBC and point to schema file
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.encoding=UTF-8
# Logging
logging.level.org.springframework=INFO
logging.level.com.accordia=DEBUG
